### ISSUE TITLE
Move to WICG?

### ISSUE THREAD

**Issue by bsittler** [WICG/async-cookies-api#31]
This discussion should probably move to WICG. I've started a topic there for it:

https://discourse.wicg.io/t/rfc-proposal-for-an-asynchronous-cookies-api/1652

**Comment by bsittler** [comment]
@annevk what do you think?

**Comment by annevk** [comment]
No opinion.

**Comment by addyosmani** [comment]
cc @cwilso @slightlyoff for their take on moving to WICG. 👍 from me for what it's worth.

**Comment by bsittler** [comment]
Moved - thanks, @cwilso ! Redirects appear to make it fairly seamless, although I have updated a few links to now-404'ing gh-pages deployment of the polyfill + tests.

**Comment by FagnerMartinsBrack** [comment]
@bsittler @annevk @addyosmani 

As an author of [js-cookie](https://github.com/js-cookie/js-cookie) I am interested in this proposal, mostly if we can create a better API to handle cookies synchronously too. js-cookie has many years of experience since jQuery Cookie days, its API was built entirely on community feedback without going overboard with unnecessary features.

Just let me know what should I do to keep up and participate if you guys believe it's worth it.

**Comment by bsittler** [comment]
@FagnerMartinsBrack welcome! I'm glad to see this isn't the only API that tries to change the default path for Set-Cookie 😄, and even more glad to have someone with much more browser experience than my own paying attention and (hopefully!) spotting obvious and not-so-obvious flaws in this proposal while it's still in early form.

Also, why synchronous? Is using await ... and/or .then(...) problematic for some reason? Are there other even handlers that need to be blocked/prevented from firing until the cookie operation completes? Or is this primarily due to a desire to use it in the inner implementation of pre-existing APIs already exporting script-blocking APIs for cookie operations?

**Comment by bsittler** [comment]
Re-closed this issue, but if you would like a parallel thread-blocking API @FagnerMartinsBrack I think that's worth opening a separate issue here, describing the reasons, and maybe giving an example or two of how it might be used.
